[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.fv.model_checker]
contracts = { "./src/SMTSolver.sol" = ["SMTSolverMath"] }
engine = "chc"
timeout = 100000
targets = ["assert", "divByZero"]
